language: go
go:
  - 1.18
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
before_script:
  - cd v2
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore "example/*.go"
